// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace org.apache.arrow.flatbuf
{

public enum Precision : short
{
 HALF = 0,
 SINGLE = 1,
 DOUBLE = 2,
};


}
