name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: input
    id: libversion
    attributes:
      label: Library Version
      description: Which version of Parquet.Net is affected?
      placeholder: ex. 4.5.1
    validations:
      required: true
  - type: input
    id: runtime
    attributes:
      label: .NET Runtime
      description: What .NET runtime you are using?
      placeholder: ex. .NET 10
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: OS and Architecture
      description: Which OS and architecture is this affecting?
      options:
        - Windows (64-bit)
        - Windows (32-bit)
        - Windows (ARM 64)
        - macOS (Intel 64-bit)
        - macOS (Apple Silicon)
        - Linux (64-bit)
        - Linux (32-bit)
        - Linux (ARM 64)
        - Other (please specify)
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: How to reproduce?
      description: Exact steps to reproduce this bug.
      value: "1. ...."
    validations:
      required: true
  - type: textarea
    id: repro-code
    attributes:
      label: Failing test
      description: Providing a failing unit test or runnable piece of code will greatly speed up issue resolution.
      render: csharp
