name: General Issue
description: Suggestions, ideas, discussons and everything that is not a bug.
title: "..."
labels: [ "triage" ]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please note that this project prohibits the use of LLMs for writing code, firing bug reports, issues, pull requests and everything else. Issues created with LLMs will be treated as spam and you account may be blocked.
  - type: textarea
    id: text
    attributes:
      label: Issue description
      description: Please describe the issue. Note that you can also use Discussions tab for general discussions.
      value: "..."
    validations:
      required: true