#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
/*
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Transport;

namespace Parquet.Thrift
{

  /// <summary>
  /// The hash function used in Bloom filter. This function takes the hash of a column value
  /// using plain encoding.
  /// 
  /// </summary>
  public partial class BloomFilterHash : TBase
  {
    private XxHash _XXHASH;

    /// <summary>
    /// xxHash Strategy. *
    /// </summary>
    public XxHash XXHASH
    {
      get
      {
        return _XXHASH;
      }
      set
      {
        __isset.XXHASH = true;
        this._XXHASH = value;
      }
    }


    public Isset __isset;
    public struct Isset {
      public bool XXHASH;
    }

    public BloomFilterHash() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct) {
                XXHASH = new XxHash();
                XXHASH.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("BloomFilterHash");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (XXHASH != null && __isset.XXHASH) {
          field.Name = "XXHASH";
          field.Type = TType.Struct;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          XXHASH.Write(oprot);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("BloomFilterHash(");
      bool __first = true;
      if (XXHASH != null && __isset.XXHASH) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("XXHASH: ");
        __sb.Append(XXHASH== null ? "<null>" : XXHASH.ToString());
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member