#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
/*
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System.Text;
using System.Threading;
using System.Threading.Tasks;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;


namespace Parquet.Thrift
{

   /// <summary>
   /// The algorithm used in Bloom filter. *
   /// </summary>
   public partial class BloomFilterAlgorithm : TBase
  {
    private SplitBlockAlgorithm _BLOCK;

    /// <summary>
    /// Block-based Bloom filter. *
    /// </summary>
    public SplitBlockAlgorithm BLOCK
    {
      get
      {
        return _BLOCK;
      }
      set
      {
        __isset.BLOCK = true;
        this._BLOCK = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool BLOCK;
    }

    public BloomFilterAlgorithm()
    {
    }

    public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct)
              {
                BLOCK = new SplitBlockAlgorithm();
                await BLOCK.ReadAsync(iprot, cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var struc = new TStruct("BloomFilterAlgorithm");
        await oprot.WriteStructBeginAsync(struc, cancellationToken);
        var field = new TField();
        if (BLOCK != null && __isset.BLOCK)
        {
          field.Name = "BLOCK";
          field.Type = TType.Struct;
          field.ID = 1;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await BLOCK.WriteAsync(oprot, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      var other = that as BloomFilterAlgorithm;
      if (other == null) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.BLOCK == other.__isset.BLOCK) && ((!__isset.BLOCK) || (System.Object.Equals(BLOCK, other.BLOCK))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if(__isset.BLOCK)
          hashcode = (hashcode * 397) + BLOCK.GetHashCode();
      }
      return hashcode;
    }

    public override string ToString()
    {
      var sb = new StringBuilder("BloomFilterAlgorithm(");
      bool __first = true;
      if (BLOCK != null && __isset.BLOCK)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("BLOCK: ");
        sb.Append(BLOCK== null ? "<null>" : BLOCK.ToString());
      }
      sb.Append(")");
      return sb.ToString();
    }
  }

}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
