#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
/*
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Parquet.Thrift
{
  /// <summary>
  /// Enum to annotate whether lists of min/max elements inside ColumnIndex
  /// are ordered and if so, in which direction.
  /// </summary>
  public enum BoundaryOrder
  {
    UNORDERED = 0,
    ASCENDING = 1,
    DESCENDING = 2,
  }
}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member