#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
/*
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System.Text;
using Thrift.Protocol;

namespace Parquet.Thrift
{
   public class ColumnChunk : TBase
   {
      private string _file_path;
      private ColumnMetaData _meta_data;

      /// <summary>
      /// File where column data is stored.  If not set, assumed to be same file as
      /// metadata.  This path is relative to the current file.
      /// 
      /// </summary>
      public string File_path
      {
         get
         {
            return _file_path;
         }
         set
         {
            __isset.file_path = true;
            this._file_path = value;
         }
      }

      /// <summary>
      /// Byte offset in file_path to the ColumnMetaData *
      /// </summary>
      public long File_offset { get; set; }

      /// <summary>
      /// Column metadata for this chunk. This is the same content as what is at
      /// file_path/file_offset.  Having it here has it replicated in the file
      /// metadata.
      /// 
      /// </summary>
      public ColumnMetaData Meta_data
      {
         get
         {
            return _meta_data;
         }
         set
         {
            __isset.meta_data = true;
            this._meta_data = value;
         }
      }


      public Isset __isset;



      public struct Isset
      {
         public bool file_path;
         public bool meta_data;
      }

      public ColumnChunk()
      {
      }

      public ColumnChunk(long file_offset) : this()
      {
         this.File_offset = file_offset;
      }

      public void Read(TProtocol iprot)
      {
         iprot.IncrementRecursionDepth();
         try
         {
            bool isset_file_offset = false;
            TField field;
            iprot.ReadStructBegin();
            while (true)
            {
               field = iprot.ReadFieldBegin();
               if (field.Type == TType.Stop)
               {
                  break;
               }
               switch (field.ID)
               {
                  case 1:
                     if (field.Type == TType.String)
                     {
                        File_path = iprot.ReadString();
                     }
                     else
                     {
                        TProtocolUtil.Skip(iprot, field.Type);
                     }
                     break;
                  case 2:
                     if (field.Type == TType.I64)
                     {
                        File_offset = iprot.ReadI64();
                        isset_file_offset = true;
                     }
                     else
                     {
                        TProtocolUtil.Skip(iprot, field.Type);
                     }
                     break;
                  case 3:
                     if (field.Type == TType.Struct)
                     {
                        Meta_data = new ColumnMetaData();
                        Meta_data.Read(iprot);
                     }
                     else
                     {
                        TProtocolUtil.Skip(iprot, field.Type);
                     }
                     break;
                  default:
                     TProtocolUtil.Skip(iprot, field.Type);
                     break;
               }
               iprot.ReadFieldEnd();
            }
            iprot.ReadStructEnd();
            if (!isset_file_offset)
               throw new TProtocolException(TProtocolException.INVALID_DATA);
         }
         finally
         {
            iprot.DecrementRecursionDepth();
         }
      }

      public void Write(TProtocol oprot)
      {
         oprot.IncrementRecursionDepth();
         try
         {
            TStruct struc = new TStruct("ColumnChunk");
            oprot.WriteStructBegin(struc);
            TField field = new TField();
            if (File_path != null && __isset.file_path)
            {
               field.Name = "file_path";
               field.Type = TType.String;
               field.ID = 1;
               oprot.WriteFieldBegin(field);
               oprot.WriteString(File_path);
               oprot.WriteFieldEnd();
            }
            field.Name = "file_offset";
            field.Type = TType.I64;
            field.ID = 2;
            oprot.WriteFieldBegin(field);
            oprot.WriteI64(File_offset);
            oprot.WriteFieldEnd();
            if (Meta_data != null && __isset.meta_data)
            {
               field.Name = "meta_data";
               field.Type = TType.Struct;
               field.ID = 3;
               oprot.WriteFieldBegin(field);
               Meta_data.Write(oprot);
               oprot.WriteFieldEnd();
            }
            oprot.WriteFieldStop();
            oprot.WriteStructEnd();
         }
         finally
         {
            oprot.DecrementRecursionDepth();
         }
      }

      public override string ToString()
      {
         StringBuilder __sb = new StringBuilder("ColumnChunk(");
         bool __first = true;
         if (File_path != null && __isset.file_path)
         {
            if (!__first) { __sb.Append(", "); }
            __first = false;
            __sb.Append("File_path: ");
            __sb.Append(File_path);
         }
         if (!__first) { __sb.Append(", "); }
         __sb.Append("File_offset: ");
         __sb.Append(File_offset);
         if (Meta_data != null && __isset.meta_data)
         {
            __sb.Append(", Meta_data: ");
            __sb.Append(Meta_data == null ? "<null>" : Meta_data.ToString());
         }
         __sb.Append(")");
         return __sb.ToString();
      }

   }

}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member