#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
/*
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Transport;

namespace Parquet.Thrift
{


  public partial class ColumnCryptoMetaData : TBase
  {
    private EncryptionWithFooterKey _ENCRYPTION_WITH_FOOTER_KEY;
    private EncryptionWithColumnKey _ENCRYPTION_WITH_COLUMN_KEY;

    public EncryptionWithFooterKey ENCRYPTION_WITH_FOOTER_KEY
    {
      get
      {
        return _ENCRYPTION_WITH_FOOTER_KEY;
      }
      set
      {
        __isset.ENCRYPTION_WITH_FOOTER_KEY = true;
        this._ENCRYPTION_WITH_FOOTER_KEY = value;
      }
    }

    public EncryptionWithColumnKey ENCRYPTION_WITH_COLUMN_KEY
    {
      get
      {
        return _ENCRYPTION_WITH_COLUMN_KEY;
      }
      set
      {
        __isset.ENCRYPTION_WITH_COLUMN_KEY = true;
        this._ENCRYPTION_WITH_COLUMN_KEY = value;
      }
    }


    public Isset __isset;

    public struct Isset {
      public bool ENCRYPTION_WITH_FOOTER_KEY;
      public bool ENCRYPTION_WITH_COLUMN_KEY;
    }

    public ColumnCryptoMetaData() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct) {
                ENCRYPTION_WITH_FOOTER_KEY = new EncryptionWithFooterKey();
                ENCRYPTION_WITH_FOOTER_KEY.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.Struct) {
                ENCRYPTION_WITH_COLUMN_KEY = new EncryptionWithColumnKey();
                ENCRYPTION_WITH_COLUMN_KEY.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("ColumnCryptoMetaData");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (ENCRYPTION_WITH_FOOTER_KEY != null && __isset.ENCRYPTION_WITH_FOOTER_KEY) {
          field.Name = "ENCRYPTION_WITH_FOOTER_KEY";
          field.Type = TType.Struct;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          ENCRYPTION_WITH_FOOTER_KEY.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (ENCRYPTION_WITH_COLUMN_KEY != null && __isset.ENCRYPTION_WITH_COLUMN_KEY) {
          field.Name = "ENCRYPTION_WITH_COLUMN_KEY";
          field.Type = TType.Struct;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          ENCRYPTION_WITH_COLUMN_KEY.Write(oprot);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("ColumnCryptoMetaData(");
      bool __first = true;
      if (ENCRYPTION_WITH_FOOTER_KEY != null && __isset.ENCRYPTION_WITH_FOOTER_KEY) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ENCRYPTION_WITH_FOOTER_KEY: ");
        __sb.Append(ENCRYPTION_WITH_FOOTER_KEY== null ? "<null>" : ENCRYPTION_WITH_FOOTER_KEY.ToString());
      }
      if (ENCRYPTION_WITH_COLUMN_KEY != null && __isset.ENCRYPTION_WITH_COLUMN_KEY) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ENCRYPTION_WITH_COLUMN_KEY: ");
        __sb.Append(ENCRYPTION_WITH_COLUMN_KEY== null ? "<null>" : ENCRYPTION_WITH_COLUMN_KEY.ToString());
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member