#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
/*
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Transport;

namespace Parquet.Thrift
{

  /// <summary>
  /// Description for ColumnIndex.
  /// Each &lt;array-field>[i] refers to the page at OffsetIndex.page_locations[i]
  /// </summary>
  public partial class ColumnIndex : TBase
  {
    private List<long> _null_counts;

    /// <summary>
    /// A list of Boolean values to determine the validity of the corresponding
    /// min and max values. If true, a page contains only null values, and writers
    /// have to set the corresponding entries in min_values and max_values to
    /// byte[0], so that all lists have the same length. If false, the
    /// corresponding entries in min_values and max_values must be valid.
    /// </summary>
    public List<bool> Null_pages { get; set; }

    /// <summary>
    /// Two lists containing lower and upper bounds for the values of each page.
    /// These may be the actual minimum and maximum values found on a page, but
    /// can also be (more compact) values that do not exist on a page. For
    /// example, instead of storing ""Blart Versenwald III", a writer may set
    /// min_values[i]="B", max_values[i]="C". Such more compact values must still
    /// be valid values within the column's logical type. Readers must make sure
    /// that list entries are populated before using them by inspecting null_pages.
    /// </summary>
    public List<byte[]> Min_values { get; set; }

    public List<byte[]> Max_values { get; set; }

      /// <summary>
      /// Stores whether both min_values and max_values are orderd and if so, in
      /// which direction. This allows readers to perform binary searches in both
      /// lists. Readers cannot assume that max_values[i] &lt;= min_values[i+1], even
      /// if the lists are ordered.
      /// 
      /// <seealso cref="BoundaryOrder"/>
      /// </summary>
      public BoundaryOrder Boundary_order { get; set; }

    /// <summary>
    /// A list containing the number of null values for each page *
    /// </summary>
    public List<long> Null_counts
    {
      get
      {
        return _null_counts;
      }
      set
      {
        __isset.null_counts = true;
        this._null_counts = value;
      }
    }


    public Isset __isset;
    public struct Isset {
      public bool null_counts;
    }

    public ColumnIndex() {
    }

    public ColumnIndex(List<bool> null_pages, List<byte[]> min_values, List<byte[]> max_values, BoundaryOrder boundary_order) : this() {
      this.Null_pages = null_pages;
      this.Min_values = min_values;
      this.Max_values = max_values;
      this.Boundary_order = boundary_order;
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_null_pages = false;
        bool isset_min_values = false;
        bool isset_max_values = false;
        bool isset_boundary_order = false;
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.List) {
                {
                  Null_pages = new List<bool>();
                  TList _list32 = iprot.ReadListBegin();
                  for( int _i33 = 0; _i33 < _list32.Count; ++_i33)
                  {
                    bool _elem34;
                    _elem34 = iprot.ReadBool();
                    Null_pages.Add(_elem34);
                  }
                  iprot.ReadListEnd();
                }
                isset_null_pages = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.List) {
                {
                  Min_values = new List<byte[]>();
                  TList _list35 = iprot.ReadListBegin();
                  for( int _i36 = 0; _i36 < _list35.Count; ++_i36)
                  {
                    byte[] _elem37;
                    _elem37 = iprot.ReadBinary();
                    Min_values.Add(_elem37);
                  }
                  iprot.ReadListEnd();
                }
                isset_min_values = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.List) {
                {
                  Max_values = new List<byte[]>();
                  TList _list38 = iprot.ReadListBegin();
                  for( int _i39 = 0; _i39 < _list38.Count; ++_i39)
                  {
                    byte[] _elem40;
                    _elem40 = iprot.ReadBinary();
                    Max_values.Add(_elem40);
                  }
                  iprot.ReadListEnd();
                }
                isset_max_values = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.I32) {
                Boundary_order = (BoundaryOrder)iprot.ReadI32();
                isset_boundary_order = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 5:
              if (field.Type == TType.List) {
                {
                  Null_counts = new List<long>();
                  TList _list41 = iprot.ReadListBegin();
                  for( int _i42 = 0; _i42 < _list41.Count; ++_i42)
                  {
                    long _elem43;
                    _elem43 = iprot.ReadI64();
                    Null_counts.Add(_elem43);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
        if (!isset_null_pages)
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        if (!isset_min_values)
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        if (!isset_max_values)
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        if (!isset_boundary_order)
          throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("ColumnIndex");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        field.Name = "null_pages";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Bool, Null_pages.Count));
          foreach (bool _iter44 in Null_pages)
          {
            oprot.WriteBool(_iter44);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
        field.Name = "min_values";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.String, Min_values.Count));
          foreach (byte[] _iter45 in Min_values)
          {
            oprot.WriteBinary(_iter45);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
        field.Name = "max_values";
        field.Type = TType.List;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.String, Max_values.Count));
          foreach (byte[] _iter46 in Max_values)
          {
            oprot.WriteBinary(_iter46);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
        field.Name = "boundary_order";
        field.Type = TType.I32;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32((int)Boundary_order);
        oprot.WriteFieldEnd();
        if (Null_counts != null && __isset.null_counts) {
          field.Name = "null_counts";
          field.Type = TType.List;
          field.ID = 5;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.I64, Null_counts.Count));
            foreach (long _iter47 in Null_counts)
            {
              oprot.WriteI64(_iter47);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("ColumnIndex(");
      __sb.Append(", Null_pages: ");
      __sb.Append(Null_pages);
      __sb.Append(", Min_values: ");
      __sb.Append(Min_values);
      __sb.Append(", Max_values: ");
      __sb.Append(Max_values);
      __sb.Append(", Boundary_order: ");
      __sb.Append(Boundary_order);
      if (Null_counts != null && __isset.null_counts) {
        __sb.Append(", Null_counts: ");
        __sb.Append(Null_counts);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member