#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
/*
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System.Text;
using System.Threading;
using System.Threading.Tasks;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;


namespace Parquet.Thrift
{

   /// <summary>
   /// Data page header
   /// </summary>
   public partial class DataPageHeader : TBase
  {
    private Statistics _statistics;

    /// <summary>
    /// Number of values, including NULLs, in this data page. *
    /// </summary>
    public int Num_values { get; set; }

    /// <summary>
    /// Encoding used for this data page *
    /// 
    /// <seealso cref="Encoding"/>
    /// </summary>
    public Encoding Encoding { get; set; }

    /// <summary>
    /// Encoding used for definition levels *
    /// 
    /// <seealso cref="Encoding"/>
    /// </summary>
    public Encoding Definition_level_encoding { get; set; }

    /// <summary>
    /// Encoding used for repetition levels *
    /// 
    /// <seealso cref="Encoding"/>
    /// </summary>
    public Encoding Repetition_level_encoding { get; set; }

    /// <summary>
    /// Optional statistics for the data in this page*
    /// </summary>
    public Statistics Statistics
    {
      get
      {
        return _statistics;
      }
      set
      {
        __isset.statistics = true;
        this._statistics = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool statistics;
    }

    public DataPageHeader()
    {
    }

    public DataPageHeader(int num_values, Encoding encoding, Encoding definition_level_encoding, Encoding repetition_level_encoding) : this()
    {
      this.Num_values = num_values;
      this.Encoding = encoding;
      this.Definition_level_encoding = definition_level_encoding;
      this.Repetition_level_encoding = repetition_level_encoding;
    }

    public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_num_values = false;
        bool isset_encoding = false;
        bool isset_definition_level_encoding = false;
        bool isset_repetition_level_encoding = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32)
              {
                Num_values = await iprot.ReadI32Async(cancellationToken);
                isset_num_values = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.I32)
              {
                Encoding = (Encoding)await iprot.ReadI32Async(cancellationToken);
                isset_encoding = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3:
              if (field.Type == TType.I32)
              {
                Definition_level_encoding = (Encoding)await iprot.ReadI32Async(cancellationToken);
                isset_definition_level_encoding = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 4:
              if (field.Type == TType.I32)
              {
                Repetition_level_encoding = (Encoding)await iprot.ReadI32Async(cancellationToken);
                isset_repetition_level_encoding = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 5:
              if (field.Type == TType.Struct)
              {
                Statistics = new Statistics();
                await Statistics.ReadAsync(iprot, cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_num_values)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_encoding)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_definition_level_encoding)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_repetition_level_encoding)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var struc = new TStruct("DataPageHeader");
        await oprot.WriteStructBeginAsync(struc, cancellationToken);
        var field = new TField();
        field.Name = "num_values";
        field.Type = TType.I32;
        field.ID = 1;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteI32Async(Num_values, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        field.Name = "encoding";
        field.Type = TType.I32;
        field.ID = 2;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteI32Async((int)Encoding, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        field.Name = "definition_level_encoding";
        field.Type = TType.I32;
        field.ID = 3;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteI32Async((int)Definition_level_encoding, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        field.Name = "repetition_level_encoding";
        field.Type = TType.I32;
        field.ID = 4;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteI32Async((int)Repetition_level_encoding, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        if (Statistics != null && __isset.statistics)
        {
          field.Name = "statistics";
          field.Type = TType.Struct;
          field.ID = 5;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await Statistics.WriteAsync(oprot, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      var other = that as DataPageHeader;
      if (other == null) return false;
      if (ReferenceEquals(this, other)) return true;
      return System.Object.Equals(Num_values, other.Num_values)
        && System.Object.Equals(Encoding, other.Encoding)
        && System.Object.Equals(Definition_level_encoding, other.Definition_level_encoding)
        && System.Object.Equals(Repetition_level_encoding, other.Repetition_level_encoding)
        && ((__isset.statistics == other.__isset.statistics) && ((!__isset.statistics) || (System.Object.Equals(Statistics, other.Statistics))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        hashcode = (hashcode * 397) + Num_values.GetHashCode();
        hashcode = (hashcode * 397) + Encoding.GetHashCode();
        hashcode = (hashcode * 397) + Definition_level_encoding.GetHashCode();
        hashcode = (hashcode * 397) + Repetition_level_encoding.GetHashCode();
        if(__isset.statistics)
          hashcode = (hashcode * 397) + Statistics.GetHashCode();
      }
      return hashcode;
    }

    public override string ToString()
    {
      var sb = new StringBuilder("DataPageHeader(");
      sb.Append(", Num_values: ");
      sb.Append(Num_values);
      sb.Append(", Encoding: ");
      sb.Append(Encoding);
      sb.Append(", Definition_level_encoding: ");
      sb.Append(Definition_level_encoding);
      sb.Append(", Repetition_level_encoding: ");
      sb.Append(Repetition_level_encoding);
      if (Statistics != null && __isset.statistics)
      {
        sb.Append(", Statistics: ");
        sb.Append(Statistics== null ? "<null>" : Statistics.ToString());
      }
      sb.Append(")");
      return sb.ToString();
    }
  }

}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
