#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
/*
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.16.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
//using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
//using Thrift.Transport;
//using Thrift.Transport.Client;
//using Thrift.Transport.Server;
//using Thrift.Processor;


#nullable disable                // suppress C# 8.0 nullable contexts (we still support earlier versions)
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Parquet.Thrift
{

  /// <summary>
  /// The dictionary page must be placed at the first position of the column chunk
  /// if it is partly or completely dictionary encoded. At most one dictionary page
  /// can be placed in a column chunk.
  /// 
  /// </summary>
  public partial class DictionaryPageHeader : TBase
  {
    private bool _is_sorted;

    /// <summary>
    /// Number of values in the dictionary *
    /// </summary>
    public int Num_values { get; set; }

    /// <summary>
    /// Encoding using this dictionary page *
    /// 
    /// <seealso cref="global::Parquet.Thrift.Encoding"/>
    /// </summary>
    public global::Parquet.Thrift.Encoding Encoding { get; set; }

    /// <summary>
    /// If true, the entries in the dictionary are sorted in ascending order *
    /// </summary>
    public bool Is_sorted
    {
      get
      {
        return _is_sorted;
      }
      set
      {
        __isset.is_sorted = true;
        this._is_sorted = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool is_sorted;
    }

    public DictionaryPageHeader()
    {
    }

    public DictionaryPageHeader(int num_values, global::Parquet.Thrift.Encoding encoding) : this()
    {
      this.Num_values = num_values;
      this.Encoding = encoding;
    }

    public DictionaryPageHeader DeepCopy()
    {
      var tmp97 = new DictionaryPageHeader();
      tmp97.Num_values = this.Num_values;
      tmp97.Encoding = this.Encoding;
      if(__isset.is_sorted)
      {
        tmp97.Is_sorted = this.Is_sorted;
      }
      tmp97.__isset.is_sorted = this.__isset.is_sorted;
      return tmp97;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_num_values = false;
        bool isset_encoding = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32)
              {
                Num_values = await iprot.ReadI32Async(cancellationToken);
                isset_num_values = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.I32)
              {
                Encoding = (global::Parquet.Thrift.Encoding)await iprot.ReadI32Async(cancellationToken);
                isset_encoding = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3:
              if (field.Type == TType.Bool)
              {
                Is_sorted = await iprot.ReadBoolAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_num_values)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_encoding)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp98 = new TStruct("DictionaryPageHeader");
        await oprot.WriteStructBeginAsync(tmp98, cancellationToken);
        var tmp99 = new TField();
        tmp99.Name = "num_values";
        tmp99.Type = TType.I32;
        tmp99.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp99, cancellationToken);
        await oprot.WriteI32Async(Num_values, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        tmp99.Name = "encoding";
        tmp99.Type = TType.I32;
        tmp99.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp99, cancellationToken);
        await oprot.WriteI32Async((int)Encoding, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        if(__isset.is_sorted)
        {
          tmp99.Name = "is_sorted";
          tmp99.Type = TType.Bool;
          tmp99.ID = 3;
          await oprot.WriteFieldBeginAsync(tmp99, cancellationToken);
          await oprot.WriteBoolAsync(Is_sorted, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is DictionaryPageHeader other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return global::System.Object.Equals(Num_values, other.Num_values)
        && global::System.Object.Equals(Encoding, other.Encoding)
        && ((__isset.is_sorted == other.__isset.is_sorted) && ((!__isset.is_sorted) || (global::System.Object.Equals(Is_sorted, other.Is_sorted))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        hashcode = (hashcode * 397) + Num_values.GetHashCode();
        hashcode = (hashcode * 397) + Encoding.GetHashCode();
        if(__isset.is_sorted)
        {
          hashcode = (hashcode * 397) + Is_sorted.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp100 = new StringBuilder("DictionaryPageHeader(");
      tmp100.Append(", Num_values: ");
      Num_values.ToString(tmp100);
      tmp100.Append(", Encoding: ");
      Encoding.ToString(tmp100);
      if(__isset.is_sorted)
      {
        tmp100.Append(", Is_sorted: ");
        Is_sorted.ToString(tmp100);
      }
      tmp100.Append(')');
      return tmp100.ToString();
    }
  }

}
