#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
/*
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Transport;

namespace Parquet.Thrift
{


  public partial class EncryptionAlgorithm : TBase
  {
    private AesGcmV1 _AES_GCM_V1;
    private AesGcmCtrV1 _AES_GCM_CTR_V1;

    public AesGcmV1 AES_GCM_V1
    {
      get
      {
        return _AES_GCM_V1;
      }
      set
      {
        __isset.AES_GCM_V1 = true;
        this._AES_GCM_V1 = value;
      }
    }

    public AesGcmCtrV1 AES_GCM_CTR_V1
    {
      get
      {
        return _AES_GCM_CTR_V1;
      }
      set
      {
        __isset.AES_GCM_CTR_V1 = true;
        this._AES_GCM_CTR_V1 = value;
      }
    }


    public Isset __isset;

    public struct Isset {
      public bool AES_GCM_V1;
      public bool AES_GCM_CTR_V1;
    }

    public EncryptionAlgorithm() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct) {
                AES_GCM_V1 = new AesGcmV1();
                AES_GCM_V1.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.Struct) {
                AES_GCM_CTR_V1 = new AesGcmCtrV1();
                AES_GCM_CTR_V1.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("EncryptionAlgorithm");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (AES_GCM_V1 != null && __isset.AES_GCM_V1) {
          field.Name = "AES_GCM_V1";
          field.Type = TType.Struct;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          AES_GCM_V1.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (AES_GCM_CTR_V1 != null && __isset.AES_GCM_CTR_V1) {
          field.Name = "AES_GCM_CTR_V1";
          field.Type = TType.Struct;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          AES_GCM_CTR_V1.Write(oprot);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("EncryptionAlgorithm(");
      bool __first = true;
      if (AES_GCM_V1 != null && __isset.AES_GCM_V1) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("AES_GCM_V1: ");
        __sb.Append(AES_GCM_V1== null ? "<null>" : AES_GCM_V1.ToString());
      }
      if (AES_GCM_CTR_V1 != null && __isset.AES_GCM_CTR_V1) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("AES_GCM_CTR_V1: ");
        __sb.Append(AES_GCM_CTR_V1== null ? "<null>" : AES_GCM_CTR_V1.ToString());
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member