#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
/*
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.16.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
//using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
//using Thrift.Transport;
//using Thrift.Transport.Client;
//using Thrift.Transport.Server;
//using Thrift.Processor;


#nullable disable                // suppress C# 8.0 nullable contexts (we still support earlier versions)
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Parquet.Thrift
{

  /// <summary>
  /// Integer logical type annotation
  /// 
  /// bitWidth must be 8, 16, 32, or 64.
  /// 
  /// Allowed for physical types: INT32, INT64
  /// </summary>
  public partial class IntType : TBase
  {

    public sbyte BitWidth { get; set; }

    public bool IsSigned { get; set; }

    public IntType()
    {
    }

    public IntType(sbyte bitWidth, bool isSigned) : this()
    {
      this.BitWidth = bitWidth;
      this.IsSigned = isSigned;
    }

    public IntType DeepCopy()
    {
      var tmp65 = new IntType();
      tmp65.BitWidth = this.BitWidth;
      tmp65.IsSigned = this.IsSigned;
      return tmp65;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_bitWidth = false;
        bool isset_isSigned = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Byte)
              {
                BitWidth = await iprot.ReadByteAsync(cancellationToken);
                isset_bitWidth = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.Bool)
              {
                IsSigned = await iprot.ReadBoolAsync(cancellationToken);
                isset_isSigned = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_bitWidth)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_isSigned)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp66 = new TStruct("IntType");
        await oprot.WriteStructBeginAsync(tmp66, cancellationToken);
        var tmp67 = new TField();
        tmp67.Name = "bitWidth";
        tmp67.Type = TType.Byte;
        tmp67.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp67, cancellationToken);
        await oprot.WriteByteAsync(BitWidth, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        tmp67.Name = "isSigned";
        tmp67.Type = TType.Bool;
        tmp67.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp67, cancellationToken);
        await oprot.WriteBoolAsync(IsSigned, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is IntType other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return global::System.Object.Equals(BitWidth, other.BitWidth)
        && global::System.Object.Equals(IsSigned, other.IsSigned);
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        hashcode = (hashcode * 397) + BitWidth.GetHashCode();
        hashcode = (hashcode * 397) + IsSigned.GetHashCode();
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp68 = new StringBuilder("IntType(");
      tmp68.Append(", BitWidth: ");
      BitWidth.ToString(tmp68);
      tmp68.Append(", IsSigned: ");
      IsSigned.ToString(tmp68);
      tmp68.Append(')');
      return tmp68.ToString();
    }
  }

}
