#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
/*
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Parquet.Thrift
{
   public enum PageType
   {
      DATA_PAGE = 0,
      INDEX_PAGE = 1,
      DICTIONARY_PAGE = 2,
      DATA_PAGE_V2 = 3,
   }
}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member