#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
/*
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.16.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
//using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
//using Thrift.Transport;
//using Thrift.Transport.Client;
//using Thrift.Transport.Server;
//using Thrift.Processor;


#nullable disable                // suppress C# 8.0 nullable contexts (we still support earlier versions)
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Parquet.Thrift
{

  public partial class PageLocation : TBase
  {

    /// <summary>
    /// Offset of the page in the file *
    /// </summary>
    public long Offset { get; set; }

    /// <summary>
    /// Size of the page, including header. Sum of compressed_page_size and header
    /// length
    /// </summary>
    public int Compressed_page_size { get; set; }

    /// <summary>
    /// Index within the RowGroup of the first row of the page; this means pages
    /// change on record boundaries (r = 0).
    /// </summary>
    public long First_row_index { get; set; }

    public PageLocation()
    {
    }

    public PageLocation(long offset, int compressed_page_size, long first_row_index) : this()
    {
      this.Offset = offset;
      this.Compressed_page_size = compressed_page_size;
      this.First_row_index = first_row_index;
    }

    public PageLocation DeepCopy()
    {
      var tmp225 = new PageLocation();
      tmp225.Offset = this.Offset;
      tmp225.Compressed_page_size = this.Compressed_page_size;
      tmp225.First_row_index = this.First_row_index;
      return tmp225;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_offset = false;
        bool isset_compressed_page_size = false;
        bool isset_first_row_index = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I64)
              {
                Offset = await iprot.ReadI64Async(cancellationToken);
                isset_offset = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.I32)
              {
                Compressed_page_size = await iprot.ReadI32Async(cancellationToken);
                isset_compressed_page_size = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3:
              if (field.Type == TType.I64)
              {
                First_row_index = await iprot.ReadI64Async(cancellationToken);
                isset_first_row_index = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_offset)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_compressed_page_size)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_first_row_index)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp226 = new TStruct("PageLocation");
        await oprot.WriteStructBeginAsync(tmp226, cancellationToken);
        var tmp227 = new TField();
        tmp227.Name = "offset";
        tmp227.Type = TType.I64;
        tmp227.ID = 1;
        await oprot.WriteFieldBeginAsync(tmp227, cancellationToken);
        await oprot.WriteI64Async(Offset, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        tmp227.Name = "compressed_page_size";
        tmp227.Type = TType.I32;
        tmp227.ID = 2;
        await oprot.WriteFieldBeginAsync(tmp227, cancellationToken);
        await oprot.WriteI32Async(Compressed_page_size, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        tmp227.Name = "first_row_index";
        tmp227.Type = TType.I64;
        tmp227.ID = 3;
        await oprot.WriteFieldBeginAsync(tmp227, cancellationToken);
        await oprot.WriteI64Async(First_row_index, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is PageLocation other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return global::System.Object.Equals(Offset, other.Offset)
        && global::System.Object.Equals(Compressed_page_size, other.Compressed_page_size)
        && global::System.Object.Equals(First_row_index, other.First_row_index);
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        hashcode = (hashcode * 397) + Offset.GetHashCode();
        hashcode = (hashcode * 397) + Compressed_page_size.GetHashCode();
        hashcode = (hashcode * 397) + First_row_index.GetHashCode();
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp228 = new StringBuilder("PageLocation(");
      tmp228.Append(", Offset: ");
      Offset.ToString(tmp228);
      tmp228.Append(", Compressed_page_size: ");
      Compressed_page_size.ToString(tmp228);
      tmp228.Append(", First_row_index: ");
      First_row_index.ToString(tmp228);
      tmp228.Append(')');
      return tmp228.ToString();
    }
  }

}
