#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
/*
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Transport;

namespace Parquet.Thrift
{


  public partial class TimeUnit : TBase
  {
    private MilliSeconds _MILLIS;
    private MicroSeconds _MICROS;
    private NanoSeconds _NANOS;

    public MilliSeconds MILLIS
    {
      get
      {
        return _MILLIS;
      }
      set
      {
        __isset.MILLIS = true;
        this._MILLIS = value;
      }
    }

    public MicroSeconds MICROS
    {
      get
      {
        return _MICROS;
      }
      set
      {
        __isset.MICROS = true;
        this._MICROS = value;
      }
    }

    public NanoSeconds NANOS
    {
      get
      {
        return _NANOS;
      }
      set
      {
        __isset.NANOS = true;
        this._NANOS = value;
      }
    }


    public Isset __isset;

    public struct Isset {
      public bool MILLIS;
      public bool MICROS;
      public bool NANOS;
    }

    public TimeUnit() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct) {
                MILLIS = new MilliSeconds();
                MILLIS.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.Struct) {
                MICROS = new MicroSeconds();
                MICROS.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.Struct) {
                NANOS = new NanoSeconds();
                NANOS.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("TimeUnit");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (MILLIS != null && __isset.MILLIS) {
          field.Name = "MILLIS";
          field.Type = TType.Struct;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          MILLIS.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (MICROS != null && __isset.MICROS) {
          field.Name = "MICROS";
          field.Type = TType.Struct;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          MICROS.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (NANOS != null && __isset.NANOS) {
          field.Name = "NANOS";
          field.Type = TType.Struct;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          NANOS.Write(oprot);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("TimeUnit(");
      bool __first = true;
      if (MILLIS != null && __isset.MILLIS) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("MILLIS: ");
        __sb.Append(MILLIS== null ? "<null>" : MILLIS.ToString());
      }
      if (MICROS != null && __isset.MICROS) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("MICROS: ");
        __sb.Append(MICROS== null ? "<null>" : MICROS.ToString());
      }
      if (NANOS != null && __isset.NANOS) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("NANOS: ");
        __sb.Append(NANOS== null ? "<null>" : NANOS.ToString());
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member