name: 'Build'

on:
  push:
    branches:
    - master
    paths-ignore:
    - 'docs/**'

  pull_request:
    branches:
    - master
    paths-ignore:
    - 'docs/**'

  workflow_dispatch:

jobs:
  test:
    name: 🧪 Unit Tests - ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux x64
          - os: windows-latest
            name: Windows x64
          - os: macos-latest
            name: MacOS ARM64
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.0.x
          8.0.x
          9.0.x
          10.0.x
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Install Python dependencies
      run: pip install pyarrow pandas

    - name: 'test'
      run: dotnet test src/Parquet.slnx -c release

  benchmark:
    name: ⚖️ High-Level Benchmarks
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux x64
          - os: windows-latest
            name: Windows x64
          - os: macos-latest
            name: MacOS ARM64
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Run Benchmarks
      run: |
        dotnet run -c release -- highLevel
      working-directory: src/Parquet.PerfRunner

  build:

    runs-on: 'ubuntu-latest'
    name: '🏛️ Build NuGet'

    steps:

    - uses: actions/checkout@v4
  
    # note that >>$GITHUB_ENV only exposes the variable to the next steps, not the current one, so we need to echo it here for the current step
    - name: create variables
      run: |
        VERSION=$(cat docs/release-notes.md | head -n 1 | xargs | tr -d ' \#')
        VERSION_MAJOR=$(echo $VERSION | cut -d. -f1).0.0
        VERSION_NO_SUFFIX=$(echo $VERSION | cut -d- -f1)

        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "VERSION_MAJOR=$VERSION_MAJOR" >> $GITHUB_ENV
        echo "VERSION_NO_SUFFIX=$VERSION_NO_SUFFIX" >> $GITHUB_ENV

    - name: print variables
      run: |
        echo head_ref: ${{ github.head_ref }}
        echo run id: ${{ github.run_id }}
        echo VERSION: ${{ env.VERSION }}
        echo VERSION_MAJOR: ${{ env.VERSION_MAJOR }}
        echo VERSION_NO_SUFFIX: ${{ env.VERSION_NO_SUFFIX }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.0.x
          8.0.x
          9.0.x
          10.0.x

    - name: Build Library
      run: |
        envsubst < src/Parquet/Globals.cs > g.tmp && mv g.tmp src/Parquet/Globals.cs
        cat src/Parquet/Globals.cs
        dotnet build src/Parquet.slnx -c release /p:Version=$VERSION /p:FileVersion=$VERSION_NO_SUFFIX.0 /p:AssemblyVersion=$VERSION_MAJOR.0

    - name: collect artifacts
      run: |
        mkdir artifacts
        cp src/Parquet/bin/Release/*.nupkg artifacts/
        cp src/Parquet.Data.Analysis/bin/Release/*.nupkg artifacts/
        grep -m 2 -B 1000 '^# ' docs/release-notes.md | tail -n +3 | head -n -2 > artifacts/release-notes.md
        echo $VERSION > artifacts/version.txt

    - uses: actions/upload-artifact@v4
      name: upload artifacts
      with:
        name: bin
        path: artifacts/*

  release:
    name: '🕋 Release library'
    runs-on: ubuntu-latest 
    needs:
    - test
    - build
    if: github.ref == 'refs/heads/master'

    steps:

      - name: ⬇️ Download Library binaries
        uses: actions/download-artifact@v4
        with:
          name: bin
          path: bin

      - name: print release notes
        run: cat bin/release-notes.md

      - name: 📦 Publish to NuGet
        run: dotnet nuget push bin/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

  release-all:
    name: '🕋 Make GitHub Release'
    runs-on: ubuntu-latest 
    needs:
    - release
    if: github.ref == 'refs/heads/master'

    steps:

      - name: ⬇️ Download Library binaries
        uses: actions/download-artifact@v4
        with:
          name: bin
          path: bin

      - name: 🔍 view artifacts to be used
        run: ls -R
        working-directory: .

      # https://github.com/softprops/action-gh-release
      - name: 📢 Create release
        uses: softprops/action-gh-release@v1
        if: ${{ !env.PACKAGE_SUFFIX }}
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          files: |
            bin/*.nupkg
          body_path: bin/release-notes.md
