name: 'Full Workflow'

env:
  VERSION: 4.12.0
  ASM_VERSION: 4.0.0

on:
  push:
    branches: [ master ]
    paths-ignore:
      - docs/**

  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          3.1.x
          6.0.x
          7.0.x
    - name: 'test on ${{ matrix.os }}'
      run: dotnet test src/Parquet.sln -c release


  build:

    runs-on: 'ubuntu-latest'

    steps:
    - run: echo ${{ github.head_ref }}
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          3.1.x
          6.0.x
          7.0.x
    - name: Build
      run: |
        envsubst < src/Parquet/Globals.cs > g.tmp && mv g.tmp src/Parquet/Globals.cs
        cat src/Parquet/Globals.cs
        dotnet build src/Parquet.sln -c release /p:Version=$VERSION /p:FileVersion=$VERSION /p:AssemblyVersion=$ASM_VERSION

    - uses: actions/upload-artifact@v3
      name: save
      with:
        name: nuget
        path: |
          src/Parquet/bin/Release/*.nupkg

  publish:
    needs: [build, test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    environment: nuget
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: nuget
          path: nuget/
      - name: Do It!
        run: dotnet nuget push nuget/* --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      - name: create gh release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          files: "src/Parquet/bin/Release/*.nupkg"
          generate_release_notes: true